# Generated by Django 5.0.3 on 2024-03-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_management', '0003_alter_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.URLField(null=True),
        ),
    ]
